### ISSUE TITLE
Finalize development checklist draft

### ISSUE THREAD

**Issue by wlla** [NYPL/design-toolkit#167]
Finalize first draft checklist:
- [ ] Review and revise ordering of items
- [ ] Review and revise copy for clarity
- [ ] Update test fields for all items to help standardize testing tools
- [ ] Annotate standards to identify which items apply at product, page, component, and content type levels
- [ ] Annotated standards with mobile considerations
- [ ] Decide on checkbox formatting

**Comment by EdwinGuzman** [comment]
@wlla is this still relevant?

**Comment by wlla** [comment]
I am currently revising and reformatting these checklists for various audiences, but they may be published somewhere other than the design toolkit. I'm going to close this ticket to help tidy up your issues list. When I have something actionable we can return. Sound good?

**Comment by EdwinGuzman** [comment]
It does. Thank you.
